'use client';

import { useState, useRef } from 'react';
import axios from 'axios';

interface ActionPanelProps {
  onOutput: (message: string) => void;
  onLoading: (loading: boolean) => void;
  onRosterUpdate: () => void;
}

export default function ActionPanel({ onOutput, onLoading, onRosterUpdate }: ActionPanelProps) {
  const fileInputRef = useRef<HTMLInputElement>(null);
  const attendanceFileRef = useRef<HTMLInputElement>(null);
  const [query, setQuery] = useState('');
  const [studentName, setStudentName] = useState('');
  const [dslCode, setDslCode] = useState('');
  const [attendanceDate, setAttendanceDate] = useState('');

  const API_BASE = 'http://localhost:5001/api';

  const handleLoadRoster = async () => {
    const file = fileInputRef.current?.files?.[0];
    if (!file) {
      alert('Please select a roster file');
      return;
    }

    onLoading(true);
    onOutput('Loading roster file...');

    try {
      const formData = new FormData();
      formData.append('file', file);

      const response = await axios.post(`${API_BASE}/roster/load`, formData, {
        headers: { 'Content-Type': 'multipart/form-data' },
      });

      if (response.data.success) {
        onOutput(`✓ ${response.data.message}`);
        onRosterUpdate();
      } else {
        onOutput(`✗ Error: ${response.data.error}`);
      }
    } catch (error: any) {
      onOutput(`✗ Error: ${error.response?.data?.error || error.message}`);
    } finally {
      onLoading(false);
    }
  };

  const handleProcessAttendance = async () => {
    const file = attendanceFileRef.current?.files?.[0];
    if (!file) {
      alert('Please select an attendance file');
      return;
    }

    onLoading(true);
    onOutput('Processing attendance with Gemini AI...');

    try {
      const formData = new FormData();
      formData.append('file', file);
      if (attendanceDate) {
        formData.append('date', attendanceDate);
      }

      const response = await axios.post(`${API_BASE}/attendance/process`, formData, {
        headers: { 'Content-Type': 'multipart/form-data' },
      });

      if (response.data.success) {
        onOutput('✓ DSL code generated by Gemini:');
        onOutput(response.data.dsl_code);
        setDslCode(response.data.dsl_code);
      } else {
        onOutput(`✗ Error: ${response.data.error}`);
      }
    } catch (error: any) {
      onOutput(`✗ Error: ${error.response?.data?.error || error.message}`);
    } finally {
      onLoading(false);
    }
  };

  const handleQuery = async () => {
    if (!query.trim()) {
      alert('Please enter a query');
      return;
    }

    onLoading(true);
    onOutput(`Querying: ${query}`);

    try {
      const response = await axios.post(`${API_BASE}/query`, { query });

      if (response.data.success) {
        onOutput('✓ DSL code generated by Gemini:');
        onOutput(response.data.dsl_code);
        setDslCode(response.data.dsl_code);
      } else {
        onOutput(`✗ Error: ${response.data.error}`);
      }
    } catch (error: any) {
      onOutput(`✗ Error: ${error.response?.data?.error || error.message}`);
    } finally {
      onLoading(false);
    }
  };

  const handleFindStudent = async () => {
    if (!studentName.trim()) {
      alert('Please enter a student name');
      return;
    }

    onLoading(true);
    onOutput(`Finding student: ${studentName}`);

    try {
      const response = await axios.post(`${API_BASE}/student/find`, {
        student_name: studentName,
      });

      if (response.data.success) {
        if (response.data.students.length > 0) {
          response.data.students.forEach((student: any) => {
            onOutput(`\n✓ Found: ${student.name}`);
            onOutput(`  Total Points: ${student.total_points || student.calculated_total}`);
            if (Object.keys(student.attendance).length > 0) {
              onOutput('  Attendance:');
              Object.entries(student.attendance).forEach(([date, points]) => {
                onOutput(`    ${date}: ${points} points`);
              });
            }
          });
        } else {
          onOutput('✗ Student not found');
        }
        if (response.data.dsl_code) {
          setDslCode(response.data.dsl_code);
        }
      } else {
        onOutput(`✗ Error: ${response.data.error}`);
      }
    } catch (error: any) {
      onOutput(`✗ Error: ${error.response?.data?.error || error.message}`);
    } finally {
      onLoading(false);
    }
  };

  const handleExecuteDSL = async () => {
    if (!dslCode.trim()) {
      alert('Please enter DSL code');
      return;
    }

    if (!confirm('Execute this DSL code?')) {
      return;
    }

    onLoading(true);
    onOutput('Executing DSL code...');
    onOutput(dslCode);

    try {
      const response = await axios.post(`${API_BASE}/dsl/execute`, {
        dsl_code: dslCode,
      });

      if (response.data.success) {
        onOutput('✓ DSL executed successfully');
        if (response.data.output) {
          onOutput(response.data.output);
        }
        onRosterUpdate();
      } else {
        onOutput(`✗ Error: ${response.data.error || 'Execution failed'}`);
      }
    } catch (error: any) {
      onOutput(`✗ Error: ${error.response?.data?.error || error.message}`);
    } finally {
      onLoading(false);
    }
  };

  return (
    <div className="space-y-4">
      {/* Load Roster */}
      <div className="card bg-gradient-to-br from-blue-50 to-indigo-50 border-2 border-blue-200">
        <div className="flex items-center gap-2 mb-3">
          <span className="text-xl">📁</span>
          <h3 className="font-bold text-gray-800">1. Load Roster File</h3>
        </div>
        <input
          ref={fileInputRef}
          type="file"
          accept=".xlsx,.xls,.csv"
          className="input mb-3"
        />
        <button onClick={handleLoadRoster} className="btn btn-primary w-full">
          📤 Load Roster
        </button>
      </div>

      {/* Process Attendance */}
      <div className="card bg-gradient-to-br from-purple-50 to-pink-50 border-2 border-purple-200">
        <div className="flex items-center gap-2 mb-3">
          <span className="text-xl">✅</span>
          <h3 className="font-bold text-gray-800">2. Process Attendance Record</h3>
        </div>
        <input
          ref={attendanceFileRef}
          type="file"
          accept=".xlsx,.xls,.csv"
          className="input mb-3"
        />
        <input
          type="text"
          placeholder="Date (optional, e.g., T,Nov.4)"
          value={attendanceDate}
          onChange={(e) => setAttendanceDate(e.target.value)}
          className="input mb-3"
        />
        <button onClick={handleProcessAttendance} className="btn btn-primary w-full bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-700 hover:to-pink-700">
          🤖 Process with Gemini AI
        </button>
      </div>

      {/* Query */}
      <div className="card bg-gradient-to-br from-teal-50 to-cyan-50 border-2 border-teal-200">
        <div className="flex items-center gap-2 mb-3">
          <span className="text-xl">🔍</span>
          <h3 className="font-bold text-gray-800">3. Query/View Information</h3>
        </div>
        <textarea
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          placeholder="Ask a question (e.g., 'show late students for Nov 4')"
          className="input mb-3 h-20"
        />
        <button onClick={handleQuery} className="btn btn-primary w-full bg-gradient-to-r from-teal-600 to-cyan-600 hover:from-teal-700 hover:to-cyan-700">
          💬 Query with Gemini AI
        </button>
      </div>

      {/* Find Student */}
      <div className="card bg-gradient-to-br from-orange-50 to-amber-50 border-2 border-orange-200">
        <div className="flex items-center gap-2 mb-3">
          <span className="text-xl">👤</span>
          <h3 className="font-bold text-gray-800">4. Find Student's Total Points</h3>
        </div>
        <input
          type="text"
          value={studentName}
          onChange={(e) => setStudentName(e.target.value)}
          placeholder="Student name"
          className="input mb-3"
        />
        <button onClick={handleFindStudent} className="btn btn-primary w-full bg-gradient-to-r from-orange-600 to-amber-600 hover:from-orange-700 hover:to-amber-700">
          🔎 Find Student
        </button>
      </div>

      {/* Execute DSL */}
      <div className="card bg-gradient-to-br from-indigo-50 to-purple-50 border-2 border-indigo-200">
        <div className="flex items-center gap-2 mb-3">
          <span className="text-xl">⚡</span>
          <h3 className="font-bold text-gray-800">5. Execute DSL Code</h3>
        </div>
        <textarea
          value={dslCode}
          onChange={(e) => setDslCode(e.target.value)}
          placeholder="DSL code will appear here after processing..."
          className="input mb-3 h-32 font-mono text-sm"
        />
        <button onClick={handleExecuteDSL} className="btn btn-success w-full">
          ▶️ Execute DSL
        </button>
      </div>
    </div>
  );
}

